| ID   | Work Item Type | Title                                               | Test Step | Step Action                                                                                                                                          | Step Expected                                                                                                                                                | Test Type     | Testing Techniques       | Area Path | Assigned To | State  | IBS Workflow Type |
| ---- | -------------- | --------------------------------------------------- | --------- | ---------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------- | ------------------------ | --------- | ----------- | ------ | ----------------- |
| TC01 | Test Case      | Verify remote SSH connectivity from Viya to Staging | 1         | To verify that the user is able to initiate an SSH connection from the SAS Viya interface (terminal or job) to the staging server at IP 10.7.30.xxx  | The user should be able to successfully establish an SSH connection to the staging server without timeout or permission denied errors                        | Integration   | Compatibility Testing    | ASIAQPR   | <Your Name> | Design | UAT               |
| TC02 | Test Case      | Submit SAS job from Viya and check staging response | 1         | To verify that the user can submit a basic SAS program from Viya which runs a `data _null_;` step on the staging server                              | The job should be executed successfully on the staging server and return a success status to the Viya interface                                              | Functional    | Procedure Testing        | ASIAQPR   | <Your Name> | Design | UAT               |
| TC03 | Test Case      | Verify log generation after remote job submission   | 1         | To verify that after a job is submitted from Viya, a corresponding log file is created in the staging server log directory (e.g., `/saswork/logs`)   | A log file should be created on the staging server containing execution steps, return codes, and time stamps, and should be accessible by Viya portal        | Functional    | Requirements/Functional  | ASIAQPR   | <Your Name> | Design | UAT               |
| TC04 | Test Case      | Write file to staging server’s storage directory    | 1         | To verify the ability of a SAS job (from Viya) to write an output dataset to the staging server’s 14TB storage directory (e.g., `/data/`)            | The output dataset should be created at the specified path with appropriate file size and timestamp indicating successful write operation                    | Functional    | Boundary Value Analysis  | ASIAQPR   | <Your Name> | Design | UAT               |
| TC05 | Test Case      | Execute SAS script directly on staging (local test) | 1         | To verify that a user with terminal access can directly SSH into the staging server and execute a standalone SAS script via command line             | The script should run without Viya, returning logs and output datasets locally on the staging server                                                         | Functional    | Procedure Testing        | ASIAQPR   | <Your Name> | Design | UAT               |
| TC06 | Test Case      | Disk capacity monitoring test (14TB validation)     | 1         | To verify that the system admin or monitoring tools can report disk usage from the 14TB storage, and alerts are generated if usage exceeds threshold | The `df -h` or monitoring dashboard should reflect accurate disk usage, and alerting mechanisms should notify if free space drops below configured threshold | Risk-based    | Risk Based Testing       | ASIAQPR   | <Your Name> | Design | UAT               |
| TC07 | Test Case      | Remote job failure handling from Viya               | 1         | To verify that when a SAS job with incorrect syntax or broken logic is submitted from Viya, it fails gracefully on staging                           | The job should fail, and an error message should be displayed both on the Viya portal and in the log file stored on staging server                           | Negative      | Error Handling           | ASIAQPR   | <Your Name> | Design | UAT               |
| TC08 | Test Case      | Submit multiple jobs in parallel from Viya          | 1         | To verify that multiple users or same user can submit two or more SAS jobs simultaneously from Viya to the staging server                            | All jobs should be processed either in parallel or in queue as per scheduling policy without any system conflict or crash                                    | Integration   | Parallel Testing         | ASIAQPR   | <Your Name> | Design | UAT               |
| TC09 | Test Case      | Check SSH session timeout or failure                | 1         | To verify system behavior when the SSH session from Viya to staging is left idle or abruptly terminated                                              | Session should timeout per configured policy and be logged in security logs, re-login should be possible without issue                                       | Risk-based    | State Transition Testing | ASIAQPR   | <Your Name> | Design | UAT               |
| TC10 | Test Case      | Folder access permission validation on staging      | 1         | To verify that SAS jobs submitted from Viya can only access allowed directories on the staging server and are restricted from sensitive paths        | Jobs should not be able to access directories like `/etc`, `/root`, or `/var/log`, and should return permission denied errors if attempted                   | Negative      | Compatibility Testing    | ASIAQPR   | <Your Name> | Design | UAT               |
| TC11 | Test Case      | Overwrite behavior test for same job output         | 1         | To verify that resubmitting the same SAS job with identical output path overwrites or version-controls the file                                      | Either the existing file is overwritten or a new version is created based on the job design                                                                  | Functional    | Decision Table           | ASIAQPR   | <Your Name> | Design | UAT               |
| TC12 | Test Case      | Log file retention and archival mechanism check     | 1         | To verify that old logs from SAS jobs on the staging server are rotated and archived periodically                                                    | Older log files should be compressed or moved to an archive folder as per retention policy                                                                   | Compatibility | Conversion Testing       | ASIAQPR   | <Your Name> | Design | UAT               |
| TC13 | Test Case      | Job execution with high volume input dataset        | 1         | To verify that the system can handle job execution with a large dataset input (e.g., >1GB CSV file)                                                  | The job should complete without memory errors or crash, and processed data should be accurate                                                                | Functional    | Boundary Value Analysis  | ASIAQPR   | <Your Name> | Design | UAT               |
| TC14 | Test Case      | Job chaining / dependency validation                | 1         | To verify that jobs with dependencies (e.g., Job B starts only after Job A completes) behave correctly                                               | Job B should not start if Job A fails; should only proceed upon successful completion of dependent job                                                       | Functional    | State Transition Testing | ASIAQPR   | <Your Name> | Design | UAT               |
| TC15 | Test Case      | Submit job using Viya GUI and check output          | 1         | To verify that a user can use the Viya GUI to submit a job and receive confirmation and output in the GUI                                            | Job ID should be shown, job status must be visible, and output data/logs downloadable from GUI                                                               | Usability     | Usability Testing        | ASIAQPR   | <Your Name> | Design | UAT               |
